# Generated by Django 4.1.2 on 2022-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
