# Generated by Django 4.1.2 on 2022-11-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_album_album_logo_alter_song_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="album_logo",
            field=models.ImageField(
                default="media/default/album.png", upload_to="media/albums"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(upload_to="media/songs"),
        ),
    ]
